version: '3.8'

# DISTRO=opensuse docker-compose -f docker-compose-builder.yml build --pull && DISTRO=opensuse docker-compose -f docker-compose-builder.yml push

services:
  jdkbuilder:
    image: ${DOCKER_HUB_USER_AND_REPOSITORY}:${DISTRO}${JDK_BUILDER}
    build:
      context: .
      dockerfile: Dockerfile.${DISTRO}.${JDK_BUILDER}
    hostname: ${DISTRO}${JDK_BUILDER}
    container_name: ${DISTRO}${JDK_BUILDER}
    env_file:
      - .env
